project:
  type: book
  output-dir: "docs"

lang: es

book:
  title: "Bitácoras Grupo #2, CA-204 (II-2024)"
  author: "Gabriel Sanabria Alvarado, Paola Espinoza Hernández"
  date: today 
  search: true
  repo-url: "https://github.com/gabosanabria04/BitacorasGrupo-2-CA0204-II-2024-.git"
  site-url: "https://gabosanabria04.github.io/BitacorasGrupo-2-CA0204-II-2024-/"
  repo-actions: [edit, source] 
  downloads: [pdf]
  chapters:
    - "index.qmd"
    - "bitacora-1.qmd"
    - "Bitacora-2.qmd"
    - "bitacora-3.qmd"

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto
  cache: true

from: markdown+tex_math_single_backslash+emoji
link-external-newwindow: true
