---
title: "Energía del Futuro: Análisis Global de Tendencias e Indicadores en Energías Renovables"
author: "Paola Espinoza Hernández; Gabriel Sanabria Alvarado"
format: html
editor: visual
---
# Bitácora 1

## Changelog

## Planificación

### Pregunta de Investigación
¿Qué impacto puede tener la energía renovable sobre la sociedad?
#### Definición de la idea
La idea inicial consiste en abordar la energía renovable, su producción, utilización, el intercambio que se da entre países; así como el impacto que la utilización de energías renovables puede tener sobre la sociedad como conjunto.
Este tema resulta interesante, especialmente bajo el contexto actual, puesto que es usual pensar en las energías renovables para combatir el cambio climático; sin embargo, no es tan común escuchar del impacto social que esta produce, ejemplo de ello es el cambio en los paisajes que señala Requejo en el 2012, la posibilidad de alterar el abastecimiento energético que señalan Casola y Freier en el 2018, o los efectos económicos que plantean Caraballo y García en el 2017. Este trabajo pretende abordar no solo la parte de la energía como tal, sino su impacto en los países que la produce y utilizan.
De esta manera, la idea se resume en: Considerar la producción de energías renovales en diversos países, y el impacto que esto tiene sobre ellos.
#### Conceptualización de la idea
Según la RAE, las definiciones de las palabras utilizadas en la idea son:
**Considerar:** Pensar, meditar, reflexionar algo con atención y cuidado.
**Impacto:** Huella o señal que deja.
**Energía renovable:** Energía que procede de un recurso presente en la naturaleza de manera prácticamente inagotable.
**Prácticamente:** Casi, por poco.
#### Identificación de tensiones
Las comparaciones entre países puede verse afectadas por el contexto del país, importación y exportación de energía, los recursos naturales y el tipo de energía renovable producida en cada país.
#### Reformulación de la idea en modo de pregunta
¿Qué impacto puede tener la energía renovable sobre la sociedad?
¿Cómo puedo comparar los países en materia de enegías renovables?
¿Puede la utilización de energías renovables garantizar un futuro sostenible?
¿Cuáles factores afectan la producción de energía renovable?
#### Argumentación de la pregunta
**Pregunta: ¿Qué impacto puede tener la energía renovable sobre la sociedad?**
**Contraargumentos:**
  -**Ética:** La inversión de energía renovable podría llegar a ser costosa, por lo que podrían salir perjudicados lo grupos más vulnerables.
  -**Lógica:** Las energías renovables como lo son la energía solar y eólica pueden no estar disponible dependiendo de la zona donde estén instaladas.
  -**Emocional:** La implementación de energías renovables podrían ser perjudiciales en tema de pérdida de empleo en compañías de electricidad tradicionales.

**Argumentos:**
  -**Lógica:** La energía producida con fuentes no renovables implica un riego a su propia sostenibilidad, además de la enorme contaminación que genera.
  -**Ética:** A pesar de que la inversión de la instalación de energías renovables podría ser costosa, a largo plazo, las pérdidas que genería el hecho de no realizar la instalación son mayores en temas de salud ambiental y pública. La presente generación está moralmente obligada a un correcto manejo de los recursos naturales. El uso de fuentes no renovables perjudica y acelera los distintos cambios climáticos, los cuales pueden afectar gravemente a las futuras generaciones.
  -**Emocional:** El uso de energías renovables puede provocar un mejoramiento en el estilo de vida de los próximos años en comparación a las expectativas del presente. Ocasionando que futuras familias y sociedades puedan tener un mejor desarrollo colectivo e individual.
  -**Conclusión:** La importancia de las energías renovables van más allá de combatir el cambio climático y la contaminación ambiental, debido a que esto genera mejorías en el desarrollo socio-económico, además de un aumento en la salud pública internacional.

**Pregunta: ¿Qué impacto puede tener la energía renovable sobre la sociedad?**

**Pregunta: ¿Cómo puedo comparar los países en materia de enegías renovables?**

**Pregunta: ¿Puede la utilización de energías renovables garantizar un futuro sostenible?**


#### Argumentación a través de datos

## Revisión Bibliográfica

Agencia Internacional de Energías Renovables (IRENA). (2021). Renewable Energy Statistics 2021. IRENA. https://www.irena.org/Statistics

Holme, J., Pockrandt, M., Köhler, D., Noll, M., Zaytsev, Y., Attia, S., & Biurrun, I. (2023). Effects of plant invaders on native vegetation communities and ecosystem properties across Europe: A systematic review and meta-analysis. PLOS ONE, 18(8), e0299807. https://doi.org/10.1371/journal.pone.0299807

United Nations. (n.d.). What is renewable energy? United Nations. https://www.un.org/en/climatechange/what-is-renewable-energy#:~:text=Renewable%20energy%20is%20energy%20derived,plentiful%20and%20all%20around%20us.

Requejo Liberal, J. (2012). *Energía renovable: un nuevo principio de autosuficiencia conectada. Ciudad Y Territorio Estudios Territoriales*, 44(171), 113–125. https://recyt.fecyt.es/index.php/CyTET/article/view/76112

Pou, M. Á. C., & Simón, J. M. G. (2017). Energías renovables y desarrollo económico. Un análisis para España y las grandes economías europeas*. [Renewable Energy and Economic Development. An Analysis for Spain and the Biggest European Economies] *El Trimestre Económico, 84*(3), 571-609. https://doi.org/10.20430/ete.v84i335.508

Bataineh, M. J., Marcuello, C., & Sánchez-Sellero, P. (2023). Toward sustainability: the role of social entrepreneurship in creating social-economic value in renewable energy social enterprises. *REVESCO : Revista De Estudios Cooperativos, 143*. https://doi.org/10.5209/reve.85561




### Fichas de literatura

#### La autosuficiencia conectada

-   **Título:** Energía Renovable: un nuevo principio de autosuficiencia conectada
-   **Autor**: Juan Requejo Liberal
-   **Año:** 2012
-   **Nombre del tema:** El uso de energía renovable en el camino la autosuficiencia energética.
-   **Forma de organizarlo:**
    -   **Cronológico:** Análisis hecho en 2012, de datos en la década pasada.
    -   **Metodológico:** Análisis descriptivo.
    -   **Temático:** Descripción de procesos en España, con intenciones de extenderlas al mundo.
    -   **Teoría:** El impacto de la energía renovable en la dinámica social
-   **Resumen en una oración:** La utilización de energía renovable permite volver a la autosuficiencia, e implementar la autosuficiencia conectada.
-   **Argumento central:** Los países deben optar por la autosuficiencia, y recurrir a fuentes energéticas externas solo para el restante.
-   **Problemas con el argumento o tema:** La producción de energías renovables es mucho más visible que las otras, por lo que es necesario estudiar el espacio en el que se van a colocar. Además, existe un desequilibrio en la relación campo-ciudad en cuanto a la producción de energía renovable, pues es más complejo producir energía renovable en la zona urbana que en la rural; sin embargo, también se encuentran diferencias entre las zonas rurales con centrales eléctricas y las demás.
-   **Resumen en un párrafo:** La energía renovable es una mejor opción ante el daño al medio ambiente; sin embargo, producirla es muy costoso y además, exige una detallada planificación. El sistema económico urbano-industrial creó un gran dessfase entre estos dos sectores, y llevó a un gran aumento de la población, y con ella, de la demanda de recursos. Basándose en el caso español, se expone que el uso de energía renovable representa el regreso a una sociedad consciente de las limitaciones existentes. Por ello, se propone la autosuficiencia conectada, un ciclo semiabierto en el que las regiones sean capaces de sustentar al menos la mayoría de su consumo energético, y tengan que recurrir a los recursos externos solamente para lo que no pudieron sustentar. De igual manera, se expresa que esta búsqueda de autosuficiencia puede ser aplicada a otros ámbitos.

### El cambio climático y la energía renovable
* **Título:** Renewable Energy as a Solution to Climate Change: Insights from a Comprehensive Study Across Nations.
* **Autor(es):** Keshani Attanayake, Isuru Wickramage, Udul Samarasinghe, Yasangi Ranmini, Sandali Ehalapitiya, Ruwan Jayathilaka y Shanta Yapa
* **Año:** 2023
* **Nombre del tema:** Energía renovable como alternativa para la reducción de las emisiones de CO2
Impacto de las energías renovables en la reducción de emisiones de CO₂ a nivel global.
* **Formas de Organizarlo:**
+ **Cronológico:** Datos analizados desde 1995 hasta 2021.
+ **Metodológico:** Regresión lineal, no lineal y regresión de panel para analizar la relación entre energía renovable y emisiones de CO₂.
+ **Temático:** Mitigación del cambio climático a través de la transición hacia energías renovables.
+ **Teoría:** Sostenibilidad energética y reducción de carbono.

* **Resumen de una oración:** Análisis de implementación de energías renovables para reducir las emisiones de CO2 en diferentes países.
* **Argumento central:** El cambio hacia las fuentes de energía renovable podría ser vital para amortiguar el impacto del cambio climático y disminuir las emisiones de CO2 a nivel global.
* **Problemas con el argumento o el tema:**
Puede ser un reto en los países de desarrollo en el momento de la transición energética, debido a la inversión inicial alta y la necesidad de implementación de políticas adecuadas.
* **Resumen:** El estudio estudia cómo la instauración de energías renovables influye directamente en las emisiones de CO2 en 138 países durante el período de 1995 a 2021. Da uso a técnicas de regresión para valorar las relaciones lineales y no lineales entre las energías renovables y las emisiones de CO₂. El artículo recalca la importancia del cambio a energías limpias para minimizar las emisiones de carbono, pero reconoce que los países en desarrollo enfrentan desafíos significativos en términos de inversión y políticas. Finalmente, aporta recomendaciones para que los países implementen estrategias de transición energética de acuerdo con sus contextos únicos.

### La energía renovable como estrategia para combatir el cambio climático en Brasil y Argentina
* **Título:** El nexo entre cambio climático y energía renovable en el Mercosur. Un análisis comparativo de las legislaciones de Argentina y Brasil 
* **Autores:** Laura Casola y Alexander Freier
* **Año:** 2018
* **Nombre del tema:** Estrategias para la implementación de las energías renovables
* **Forma de organizarlo:**
+ **Cronológico:** Se analizan los sucesos importantes desde 1992 hasta el 2016.
+ **Metodológico:** Análisis descriptivo
+ **Temático:** Análisis de los mecanismos de implementación de energías renovables.
+ **Teoría:** Desarrollo sostenible por medio de la utilización de energías renovables
* **Resumen en una oración:** El desarrollo sustentable es clave para combatir el cambio climático.
* **Argumento central:** Para combatir el cambio climático, es necesario realizar cambios en las estructuras y la distribución de la energía, así como en la forma de producirla.
* **Problemas con el argumento o tema:** El desarrollo sustentable es un proceso demorado, y puede poner en riesgo el abastecimiento energético del país; por tanto, los países, aunque no por ello menos comprometidos con el desarrollo sostenible, tienden a prioriar el abastecimiento de energía.
* **Resumen en un párrafo:** Dado que la causa principal del cambio climático son los gases de efecto invernadero, entre los cuales destaca el CO2, derivado principalmente de la quema de fósiles; la implementación de energías renovables es fundamental para combatir este fenómeno. Aunque se reconoce la existencia y gravedad del fenómeno, así como la importancia de reducir la emisión de gases de efecto invernadero, la inversión en reservas de combustibles fósiles sobrepasa a la inversión en energías renovables. El artículo pretende facilitar la búsqueda de estándares que faciliten la implementación de energías renovables en otros países. Específicamente, se analiza la política adoptada por Brasil y Argentina, ambos miembros de Mercosur, quien promueve la producción y utilización de enrgías renovables. Los resultados indican que Brasil se enfocan en aspectos relacionados al cambio climático como la quema de bosques o la deforestación, sobre el abastecimiento energético. Por otro lado, Argentina procura mantener el abastecimiento y el desarrollo sustentable en una misma medida de importancia. No obstante, se prioriza en ambos países la seguridad energética nacional.

### UVE de Gowin

## Parte de Escritura
