---
title: "Bitácora 3"
author: "Paola Espinoza Hernández; Gabriel Sanabria Alvarado"
format: html
output_dir: "docs"
editor: visual
nocite: |
  @*
---

### Setup {.hidden}

```{r}
#| echo: FALSE
#| warnings: FALSE
library(ggplot2)
library(dplyr)
library(palmerpenguins)
library(ggthemes)
library(cowplot)
library(tidyr)
library(purrr)
library(ggExtra)
options(scipen = 999)
```

## Planificación

### Análisis Gráfico


### Fichas de Resultados


## Parte de Escritura

La base de datos original posee varios datos de un mismo país y tipo de energía para un mismo año, lo que dificulta la graficación. Anualizar los datos utilizando el promedio de estos datos, permite una mejor graficación. Estos gráficos permiten relacionar las diversas variables, puesto que los datos siguen un mismo patrón. Sin embargo, este proceso debe hacerse para todas las variables seleccionadas. Por lo tanto, se pretende realizar la anualización de los datos, juntando las observaciones según los tipos de energía de cada país para cada

De acuerdo a los datos totales, la producción de energía renovable ha aumentado en los últimos años. Dado que los datos originales incluyen muchos datos sobre un mismo año, se realizó este mismo análisis sobre los datos anualizados. En este segundo análisis, se encontró que el patrón global está formado por ese mismo patrón en casi todos los países, a excepción de Japón. Por ello, se pretende relacionar esta diferencia con alguno de los demás factores. Además, se buscará explicar, mediante alguna otra variable, la razón por la que tanto la producción global como la producción de los países por separado ha aumentado, conjeturando la estabilidad en producción energética.

El estudio de Attanayake [-@Attanayake_Wickramage_Samarasinghe_Ranmini_Ehalapitiya_Jayathilaka_Yapa_2024] analiza cómo la instauración de energías renovables influye directamente en las emisiones de CO2 en 138 países durante el período de 1995 a 2021. Donde los países desarrollados, como Estados Unidos, China y la India, tienen la cantidad promedio de emisiones más altas. Lo cual destaca que los países mayormenre responsables de las emisiones de CO2 se han mantenido constantes durante los últimos 25 años, siendo estos principalmente los países mayor desarrollados. El estudio da uso a técnicas de regresión para valorar las relaciones lineales y no lineales entre las energías renovables y las emisiones de CO₂. El artículo recalca la importancia del cambio a energías limpias para minimizar las emisiones de carbono, pero reconoce que los países en desarrollo enfrentan desafíos significativos en términos de inversión y políticas. Finalmente, aporta recomendaciones para que los países implementen estrategias de transición energética de acuerdo con sus contextos únicos. En cuanto a nuestro análisis de datos, a partir de los datos originales, es posible determinar que un aumento en producción de energías renovables implica una disminución en las emisiones de CO2. Aunque esto es esperable, pues las energías renovables son energías más limpias que las generadas por otras fuentes, como los combustibles fósiles; tanto Japón como Francia presentan una relación directa entre las variables, es decir, un aumento en la producción implica un aumento en la emisión de CO2. De estos dos países, destaca que Japón ha reducido la producción de energías renovables en los últimos años, incumpliendo también el patrón global. Se pretende determinar algún factor que explique la tendencia inversa de estos dos países con respecto a la producción y la emisión de CO2.

Existen estudios que respaldan la información del texto anterior, como lo es "Energía renovable: un nuevo principio de autosuficiencia conectada. Ciudad Y Territorio Estudios Territoriales" de Requejo Liberal [-@RequejoLiberalJuan2012Er:u], "la generación de energía eléctrica procedente de fuentes fósiles y nucleares es una actividad contaminante, que pone en peligro el planeta, que tiene impacto sobre el medio ambiente local, que tiene riesgos no bien determinados y que generan dependencia y desequilibrios en la economía nacional" [@RequejoLiberalJuan2012Er:u, pp. 114], el cual confirma el hecho de que la implementación de energías renovables puede ser un gran apoyo para el bienestar social y económico de distintas naciones. El estudio de Attanayake [-@Attanayake_Wickramage_Samarasinghe_Ranmini_Ehalapitiya_Jayathilaka_Yapa_2024] concluye que casi todos los países destacan el hecho de que si la energía renovable se incrementa, se lograría reducir la cantidad de emisiones de CO2. El cuál recalca que las economías de desarrollo debería de dar enfásis en la inversión en energías renovables y reducir el uso de combustibles fósiles, y además, destaca que los gobiernos deberían de implementar políticas de energía renovable, con el fin de garantizar un crecimiento económico.

El documento realiza un estudio esencial para el entendimiento de la importancia de la implementación de energías renovables para el bienestar social, económico y ambiental. Destacando como la mayoría de países, a excepción de Canadá, el cual un aumento del 1% en las fuentes de energía renovables da como resultado un incremento de 10,83 millones de toneladas en las emisiones de CO2, afirman que su inversión puede ser beneficiosa para su estabilidad general. Lo cual es muy importante con respecto a otros estudios que se centraban en algún país en específico. Además, la observación la colaboración de distintos gobiernos es vital, ya que reconoce la naturaleza global del cambio climático y la necesidad de soluciones coordinadas. Esta observación conjunta y propositiva fortalece la utilidad práctica del estudio para guiar políticas energéticas hacia un desarrollo más sostenible.

Según Allan Cordero [@-Gutiérrez_2015]: "El mundo se encuentra en una encrucijada trascendental para el futuro de la energía". Con el objetivo de reducir el uso de combustibles fósiles y alcanzar la soberanía energética, Costa Rica inició su proceso hacia un modelo de desarrollo autosostenible. La energía hidráulica causa deforestación y obstaculiza el camino de los peces, lo que la descarta como una solución viable a largo plazo. La energía eólica, a pesar de la posibilidad de afectar la calidad de vida de las aves y modificar, aunque muy levemente, la fuerza o dirección del viento, destaca como una opción viable en Costa Rica. Esta energía permite la eliminación de emisiones de gases de efecto invernadero y contribuye a la independencia energética. Por ello, determinar la ubicación de los parques eólicos se ha vuelto una prioridad para las autoridades a cargo.

Esta investigación tiene gran relación con lo propuesto por Laura Casola y Alexander Freier en "El nexo entre cambio climático y energía renovable en el Mercosur. Un análisis comparativo de las legislaciones de Argentina y Brasil" [@-CasólaLaura2018Enec], pues, mientras Costa Rica prioriza a la energía eólica como una solución viable, Argentina y Brasil examinan sus diversas estrategias en relación con el enfoque de Mercosur, el cual es un bloque económico y político regional en Suramérica, incorporado en 1991 con el Tratado de Asunción. en el cual están dentro países como Argentina, Brasil, Paraguay y Uruguay. Sin embargo, cada conjunto está en busca de un poder energético, cada uno con sus distintos planes. Ambas investigaciones reconocen los impactos ambientales asociados con diferentes fuentes de energía. En el caso del artículo de Cordero [@-Gutiérrez_2015], recalca los efectos negativos de la energía hidráulica, como la deforestación y la afectación a los peces, mientras que el documento de Casola y Freier [-@CasólaLaura2018Enec] habla de problemas ambientales en Brasil, como la quema de bosques y la deforestación, relacionados con el cambio climático. Ambos hacen un llamado a encontrar alternativas más sostenibles. Ambas investigaciones concluyen que existe cierta urgencia de migrar hacia el uso de energías limpias, a pesar de que esta implementación podría tener impactos negativos en temas de económicos, debido al gran costo de las distintas instalaciones, además del posible daño a la fauna, su implementación logrará beneficiar al bienestar social, ambiental y económico a largo plazo. En la bitácora 2 se puede apreciar en base a la @fig-2.1, como los distintos países priorizan las distintas energías eólicas, esto debido a las condiciones climáticas de cada zona de las regiones.

Otro estudio relacionado es el realizado por Vega de Kuyper, J.C. y Ramírez Morales, S [-@JuanCarlosVegaDeKuyper2014Fder] llamado “Fuentes de energía, renovables y no renovables. Aplicaciones.” El documento se basa en mostrar una visión integral sobre las fuentes de energía renovables y no renovables, explorando su relevancia y aplicaciones en América Latina, especialmente en países como México, Argentina, Chile y Colombia. “Con seguridad el siglo XXI… profundizará en la investigación de la materia, desde lo microcósmico a la astronáutica y avanzando en temas energéticos tales como la fusión nuclear, las energías renovables o el despliegue del hidrógeno como una fuente energética” [@JuanCarlosVegaDeKuyper2014Fder]. Con un enfoque pedagógico, los autores proporcionan un equilibrio entre teoría y práctica, explicando los principios de generación y almacenamiento de energía, además de introducir el concepto de eficiencia energética como una herramienta clave para el futuro. Se presentan ejemplos actualizados de proyectos de energías renovables en la región, incluyendo energías como la solar o la geotérmica, así como un análisis de las barreras y oportunidades para su implementación.

Otro apoyo de este análisis es el documento "Wind energy technology and current status: a review" hecho por Thomas Ackermann y Lennart Söder [-@ACKERMANN2000315], los cuales destacan los aspectos positivos de la implementacion de la energía eólica en todas las zonas, en especial en zonas ventosas siendo más capaces de generar energía. Ambos estudios subrayan la capacidad de la energía eólica para reducir las emisiones de gases de efecto invernadero. Ellos sugieren que la expansión de las energías renovables, incluida la eólica, llevará a una disminución del uso de energías no renovables y reducirá emisiones indirectas. Además, ambos estudios indican que a pesar de que la instalación de ciertas energías renovables puede aumentar el bienestar, puede haber inconvenientes como la contaminación sónica provocada por las turbinas. No obstante, estos inconvenientes pueden ser mitigados con el paso de los años. En nuestra investigación se puede apreciar que la distribución de la conciencia pública ha sido bastante variable entre los años analizados. Comparando el 2023 con los dos años anteriores, el 2023 tiene mayor distribución en algunas áreas, específicamente las bajas. Al comparar el 2020 con el 2023, la conciencia pública es menor, pues las concentraciones de distribución se encuentran en valores más bajos. En otros años, como el 2009, la conciencia pública estaba mejor repartida entre los países, pero eso no significa que sea mejor, pues en realidad el escenario ideal es la concentración en los valores altos. Se pretende comparar los datos de la conciencia pública con respecto a la existencia o no de programas educativos sobre la energía renovable, así como la proporción de energía consumida que procede de fuentes renovables.

Tanto en los datos originales como en los anualizados de nuestro proyecto, es posible determinar que para los últimos años, los precios de la electricidad están aumentando. Sin embargo, el cambio en los precios no es realmete significativo. La pequeña magnitud de los cambios en precio, permiten conjeturar, que los precios se mantienen casi constantes. Se pretende encontrar una variable contextual a nivel global, que justifique la estabilización de los precios. Para esto último, es necesario promediar los precios de todos los países, pues como la variable representa un precio, no se deben sumar los valores.

El artículo de Abay Analistas Económicos y Sociales [@Analistas_2014] estudia la pobreza energética, que se refiere a los hogares incapaces de pagar servicios eléctricos que satisfagan sus necesidades o que destinan una cantidad excesiva a este gasto, es causada por factores como bajos ingresos, pobre acceso a la energía, ineficiencia energética o precios altos. Las consecuencias de esta pobreza abarcan tanto riesgos para la salud física como para la salud mental, además de afectar el futuro de los niños. En España, la pobreza energética va en aumento, lo que resalta la necesidad de soluciones efectivas. Por ello, el desarrollo de energías renovables es crucial, ya que disminuirá el precio promedio de la electricidad al reducir los precios mayoristas, así como los costes de inversión y el desarrollo tecnológico. Por lo tanto, la energía renovable representa un factor importante en la sostenibilidad social y económica, pues el coste marginal nulo de los recursos utilizados se refleja en un menor coste energético y, en consecuencia, en una mayor accesibilidad para la población. Un estudio relacionado es el elaborado por Agencia Internacional de Energías Renovables (IRENA) llamado "Renewable Energy Statistics 2021", el cual muestra datos específicos importantes para el seguimiento de la inauguración de nuevas políticas e implementaciones de energías renovables. El artículo señala el crecimiento considerable en los años 2018 y 2019, especialmente la energía solar y eólica. Este documento se relaciona con el realizado por Abay pues da una visión realista de como y cuanto se han invertido en energía renovable en los últimos años, mostrando como continentes como Asia, dedicen implementar constantemente de este tipo de energías para un mejoramiento económico y ambiental. Este aumento en la producción también ha elevado la proporción de energía total correspondiente a fuentes renovables.

Al analizar el flujo energético de los países durante todo el periodo, el la @fig-3.1, se observa que la diferencia entre las entradas y salidas de energía no es mucha. Las mayores diferencias se presentan en Canadá y Japón. Sin embargo, al visualizar los datos por año, en la @fig-3.2, no se observa esta estabilidad, salvo en algunos años. En particular, al enfocarse en los años recientes, se observa una disminución en ambas variables, lo que podría explicarse por el aumento en la producción, así como la tedencia a la independencia energética.

En la @fig-3.3 es posible visualizar el aumento de las importaciones y exportaciones totales conforme aumenta la producción. Esta relación podría ser interpretada como un exceso de energía en algunos países, que lleva a exportaciones, y llega a otros como importaciones. Sin embargo, en la @fig-3.4, se observa esta misma relación en cada país analizado. Por ello, se descarta la idea inicial. Además, los gráficos muestran una relación contraria a la relación intuitiva, pues es común pensar que conforme aumenta la producción, disminuyen las importaciones.

Otro punto importante analizado es que la fuerza de trabajo en el sector energético es mucho más volátil que la producción. En los últimos años, la producción de energía con fuentes renovables ha aumentado; sin embargo, la fuerza laboral no sigue el mismo patrón. La fuerza laboral de los últimos años ha sufrido muchas variaciones, no leves. La diferencia de crecimiento en la producción y la fuerza laboral plantea una interrogante sobre la capacidad a futuro de producción energética. Se pretende determinar si la inversión o el gasto en investigación y desarrollo se relacionan con la volatilidad de la fuerza laboral del sector energético.

La @fig-3.5 muestra que existe una concentración de precios en los valores cercanos a 0.3. Sin embargo, al separar los precios por países, en la @fig-3.6, esta tendencia no se mantiene en general. Esta diferencia entre la tendencia general y cada país, indica que existen diferencias entre estos, que no están siendo contempladas en los gráficos. Para explicar esta concentración en precios, se utilizan otras variables, como la existencia de políticas de gobierno. La @fig-3.7 muestra que la existencia de políticas de gobierno que impulsen la producción de energías renovables, explica muy bien la concentración en precios.

El artículo realizado por Las Naciones Unidas [-@Nations] llamado “¿Qué es la energía renovable?” nos da una explicación sobre las energías renovables e indican que obtienen se obtienen mediante fuentes naturales que se restablece rápidamente. A diferencia de los combustibles fósiles, que liberan grandes cantidades de dióxido de carbono y otros gases de efecto invernadero, las energías renovables son más limpias. No obstante, las fuentes tienen distintas dificultades, tales como la ubicación geográfica de las fuentes de energía e impactos ecológicos de algunas tecnologías, como la hidroeléctrica. Aun así, las energías renovables son más baratas y crean más empleos que los combustibles fósiles, lo que las convierte en una pieza clave para combatir el cambio climático y mejorar la sostenibilidad internacional.

Un estudio que respalda este artículo “Hacia un futuro con energía limpia y renovable” de Javier Serrano [-@SerranoJavier2022Hufc], el cual da una descripción de la electrificación y su relevancia en el mundo tecnológico, encabezado por avances como la inteligencia artificial, robótica y computación. Íñigo Segura, director de ZGR, afirma que el reto principal es la maximización del uso de la electricidad mientras se minimiza la dependencia de combustibles fósiles. Las tecnologías como el hidrógeno verde y la fusión nuclear se direccionan como soluciones clave para alcanzar la neutralidad de carbono, aunque aún enfrentan desafíos en cuanto a costos y escalabilidad. También se plantea la necesidad de algunas mejoras en la ciberseguridad en las redes eléctricas por su creciente conectividad y complejidad. La planificación a largo plazo es vital, ya que imprevistos globales pueden desestabilizar la transición energética y la disponibilidad de materias primas estratégicas.

La @fig-3.15 muestra que existe una relación positiva entre el gasto en investigación, y la cantidad de empleos. Además, se muestra que las políticas de gobierno afectan esta relación, pues aumentan ambas variables. La @fig-3.16 muestra que existe también una relación positiva entre la inversión y la cantidad de empleos, también potenciada por las políticas de gobierno. La @fig-3.17 muestra que el gasto en investigación y la inversión presentan una relación positiva entre ellas; y que, sin embargo, su distribución, mostrada en el margen del gráfico, es distinta.

Además de esto, María Ángeles Caraballo Pou y Juana María García Simón [-@CaraballoPouMaríaÁngeles2017Eryd] en "Energías renovables y desarrollo económico: Un análisis para España y las grandes economías europeas" dan una confirmación de todo lo descrito por Las Naciones unidas [-@Nations]. Las cuales estudian los distintos impactos de las energías renovables sobre el desarrollo económico en España y otras economías europeas como Alemania, Francia, Italia y Reino Unido. A través de técnicas de cointegración, los autores estudian la relación entre el crecimiento económico, el uso de energías renovables y no renovables, y la sostenibilidad, comparando los resultados entre los países. Se destaca que el aumento del uso de energías renovables no necesariamente ralentiza el crecimiento económico y puede contribuir a la sostenibilidad a largo plazo.

La @fig-3.8 muestra que conforme aumenta la producción, los precios tienden a estabilizarse. El valor en el que se estabilizan, resulta un valor interesante, pues es el mismo en el que se concentran los precios, en la @fig-3.5. En particular, como muestra la @fig-3.7, esta concentración aumenta en los países con políticas de gobierno que impulsen la utilización de energías renovables. Así, la comparación conjunta de los gráficos parece indicar que es posible alcanzar la estabilidad en los precios de la energía por medio de las energías renovables.

La @fig-3.14 muestra que a mayor cantidad de patentes, mayor cantidad de empleos en el sector. El aumento en la cantidad de patentes implica un aumento en la cantidad de energía que se puede producir, que a su vez implica un mayor número de empresas productoras, o la expansión de las empresas productoras ya existentes. Por ello, resulta intuitivo pensar en esta relación positiva entre las patentes y los empleos. La @fig-3.14 muestra que esta idea es correcta, al menos con los datos analizados. Además, resulta interesante ver que esta relación no muestra gran diferencia dependiendo de la energía renovable producida.

Con las explicación ofrecida por Las Naciones Unidas [@Nations], apoyada con la descripción de la electrificación que ofrece Serrano [-@SerranoJavier2022Hufc] y la comparación de distintas naciones que realizaron Caraballo y García [-@CaraballoPouMaríaÁngeles2017Eryd], se puede probar que, mediante una considerable inversión en las distintas energías renovables, se podría reforzar y evaluar la posibilidad de mejoría en el bienestar social, económico y ambiental, siendo estas interdependientes una de la otra, debido a que cada una crea externalidades tanto negativas como positivas. Lo cual también muestra que a pesar de que las energías renovables son vitables para un buen desarrollo a largo plazo, la sociedad está encargada de tomar conciencia y estudiar la importancia sobre este tema, para así evaluar la posibilidad de un cambio radical, así como lo es la minimización de energías no renovables.

Al comparar anualmente la conciencia pública en países con y sin programas educativos sobre la energía renovable, se encuentra una relación positiva entre estas variables. En la @fig-3.9, con los gráficos separados por año, se observa mayor concentración en mayores valores de conciencia pública para la clasificación que posee programas educativos sobre el tema. La no existencia de programas educativos muestra la diferencia de información entre la población, pues la mayoría de los gráficos no presentan concentración en valores, sino que la población está informada de manera muy diferenre. Por el contrario, la existencia de programas educativos, brinda información a la población general, de modo que la mayoría de la población se posiciona en valores cercanos. En particular, es posible observar que en el 2022, los programas educativos posicionan a la mayoría de la población en valores mayores a 5; mientras que en los países sin programas educativos, la mayoría se encuentra entre 2.5 y 7.5. Además, esta relación se ve acentuada en el @fig-3.10, con los valores generales.

A pesar de que existe una correlación lineal entre la producción y la cantidad de trabajos del sector de energías renovables, al incluir la existencia de programas educativos, se observan más características. El @fig-3.11 muestra una relación positiva entre la producción de energía renovable y la cantidad de trabajos del sector. Sin embargo, con el fin de visualizar otras características, se incluyó la existencia de programas educativos sobre la energía renovable. La @fig-3.12 muestra que la correlación lineal es mayor con programas educativos. Adicionalmente, muestra que las mayores producciones energéticas se dan en países con programas educativos, y que son además los de mayor cantidad de empleos en el sector. Esto último se apoya en la @fig-3.13, que muestra la relación positiva entre los programas educativos y la cantidad de empleos, tanto para los datos promedio, como para los datos extremos.

## Parte de reflexión

