---
title: "Bitacora 2"
author: "Paola Espinoza Hernández, Gabriel Sanabria Alvarado"
format: html
output_dir: "docs"
editor: visual
---

# Energía del Futuro: Análisis Global de Tendencias e Indicadores en Energías Renovables {.unnumbered}


## Parte de planificación

### Ordenamiento de la literatura

| Organización | | | Literatura | | |
|--------------|-----------------|-----------------|--------|------|--------|
| Tipo         | Tema general    | Tema específico | Título | Año  | Autor(es) |
| descriptivo | Energía renovable | El uso de energía renovable en el camino la autosuficiencia energética. | Energía Renovable: un nuevo principio de autosuficiencia conectada | 2012 | Juan Requejo Liberal |
| Análitico | Impacto de las energías renovables en la reducción de emisiones de CO₂ a nivel global. | Energía renovable como alternativa para la reducción de las emisiones de CO2 Impacto de las energías renovables en la reducción de emisiones de CO₂ a nivel global. | Renewable Energy as a Solution to Climate Change: Insights from a Comprehensive Study Across Nations. | 2023 | Keshani Attanayake, Isuru Wickramage, Udul Samarasinghe, Yasangi Ranmini, Sandali Ehalapitiya, Ruwan Jayathilaka y Shanta Yapa |
| Análisis descriptivo |Estrategias para la implementación de las energías renovables | El nexo entre cambio climático y energía renovable en el Mercosur. Un análisis comparativo de las legislaciones de Argentina y Brasil | La energía renovable como estrategia para combatir el cambio climático en Brasil y Argentina | 2018 | Laura Casola y Alexander Freier |
| Descriptivo | Estado actual de la energía eólica | Descripción de avances tecnológicos en la última década del siglo 20 | Wind energy technology and current status: a review | 2000 | Thomas Ackermann y Lennart Söder |
| Exploratorio | Viabilidad de las energías renovables en Costa Rica | Análisis de ventajas y desventajas de los tres tipos de energía renovable producida en Costa Rica. | Análisis de Viabilidad Ambiental del Uso de Energías Renovables en Costa Rica: Estudio de Caso de la Energía Eólica, la Hidroeléctrica y la Geotérmica | 2015 | Allan Cordero Gutiérrez |
| Metodológico | Árboles de decisión | CCC | Título 3 | 2002 | Autor 3 |
| Metodológico | Regresión logística | AAA | Título 1 | 2000 | Autor 1 |
| Metodológico | SVM | BBB | Título 2 | 2001 | Autor 2 |
| Metodológico | Árboles de decisión | CCC | Título 3 | 2002 | Autor 3 |
| Metodológico | SVM | BBB | Título 2 | 2001 | Autor 2 |
| Metodológico | Árboles de decisión | CCC | Título 3 | 2002 | Autor 3 |
## Enlaces de Literatura

La energía renovable es una mejor opción ante el daño al medio ambiente; sin embargo, producirla es muy costoso y además, exige una detallada planificación. El sistema económico urbano-industrial creó un gran dessfase entre estos dos sectores, y llevó a un gran aumento de la población, y con ella, de la demanda de recursos. Basándose en el caso español, se expone que el uso de energía renovable representa el regreso a una sociedad consciente de las limitaciones existentes. Por ello, se propone la autosuficiencia conectada, un ciclo semiabierto en el que las regiones sean capaces de sustentar al menos la mayoría de su consumo energético, y tengan que recurrir a los recursos externos solamente para lo que no pudieron sustentar. De igual manera, se expresa que esta búsqueda de autosuficiencia puede ser aplicada a otros ámbitos.

El estudio estudia cómo la instauración de energías renovables influye directamente en las emisiones de CO2 en 138 países durante el período de 1995 a 2021. Da uso a técnicas de regresión para valorar las relaciones lineales y no lineales entre las energías renovables y las emisiones de CO₂. El artículo recalca la importancia del cambio a energías limpias para minimizar las emisiones de carbono, pero reconoce que los países en desarrollo enfrentan desafíos significativos en términos de inversión y políticas. Finalmente, aporta recomendaciones para que los países implementen estrategias de transición energética de acuerdo con sus contextos únicos.

Dado que la causa principal del cambio climático son los gases de efecto invernadero, entre los cuales destaca el CO2, derivado principalmente de la quema de fósiles; la implementación de energías renovables es fundamental para combatir este fenómeno. Aunque se reconoce la existencia y gravedad del fenómeno, así como la importancia de reducir la emisión de gases de efecto invernadero, la inversión en reservas de combustibles fósiles sobrepasa a la inversión en energías renovables. El artículo pretende facilitar la búsqueda de estándares que faciliten la implementación de energías renovables en otros países. Específicamente, se analiza la política adoptada por Brasil y Argentina, ambos miembros de Mercosur, quien promueve la producción y utilización de enrgías renovables. Los resultados indican que Brasil se enfocan en aspectos relacionados al cambio climático como la quema de bosques o la deforestación, sobre el abastecimiento energético. Por otro lado, Argentina procura mantener el abastecimiento y el desarrollo sustentable en una misma medida de importancia. No obstante, se prioriza en ambos países la seguridad energética nacional.

